#!/bin/bash


source /opt/Vum-2.4/toolset/build.env
INSTALLDIR=/opt/Conpro2

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)
            ;;
        clean)  
            ;;
        install)
            $INSTALL -d $INSTALLDIR
            $INSTALL -d $INSTALLDIR/doc
            $INSTALL -C man/*.pdf $INSTALLDIR/doc
            check
            $CP thot/tex/conpro2.pdf $INSTALLDIR/doc/conpro2-2010.pdf		
            $CP fm/conpro2.pdf $INSTALLDIR/doc/conpro2-2011.pdf		
            check
            ;;
		
    esac
done
