#!/bin/bash


source /opt/Vum-2.4/toolset/build.env
INSTALLDIR=/opt/Conpro2

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install version"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)
            amake -f Amakefile.C libconpro.a
            check
            amake -f Amakefile.ml conpro.cma
            check
            ;;
        clean)  
            ;;
        version)  
            ;;
        install)
            $INSTALL -d $INSTALLDIR
            $INSTALL -d $INSTALLDIR/lib
            $INSTALL -C *.a *.h *.c $INSTALLDIR/lib
            $INSTALL -C *.mod $INSTALLDIR/lib
            $INSTALL -C *.ml $INSTALLDIR/lib
            $INSTALL -C *.mli $INSTALLDIR/lib
            $INSTALL -C interface/*.cmi *.cma $INSTALLDIR/lib
            check
            ;;
		
    esac
done
