--
-- Automatically generated by
-- CONPRO: Hardware Synthesis with an Imperative High Level Multiprocess Approach
--         (C) 2006-2008 ** BSSLAB, Dr. Stefan Bosse
--         Version 2.1 A8 **  2049142 total genes
--         Compiled on Thu Nov 27 11:07:26 CET 2008
--         Compiled by sbosse
--         Compiled on SunOS sun203 5.10 Generic_118833-33 sun4u sparc SUNW,A70

-- Process implementation of process <p1> from module <R>.
--
libIEEE
useIEEE1
useIEEE2
useIEEE3
useIEEE4
useIEEE5
useIEEE6
useIEEE7
useIEEE8
entity r_p1 is
port(
  -- Connections to external objects, components and the outside world
  signal REG_d_RD: in signed(9 downto 0);
  signal REG_d_WR: out signed(9 downto 0);
  signal REG_d_WE: out std_logic;
  signal REG_e_RD: in std_logic_vector(11 downto 0);
  signal REG_e_WR: out std_logic_vector(11 downto 0);
  signal REG_e_WE: out std_logic;
  signal REG_f_RD: in signed(3 downto 0);
  signal REG_f_WR: out signed(3 downto 0);
  signal REG_f_WE: out std_logic;
  signal REG_g_RD: in std_logic_vector(3 downto 0);
  signal REG_g_WR: out std_logic_vector(3 downto 0);
  signal REG_g_WE: out std_logic;
  signal x_WR: out signed(9 downto 0);
  signal y_WR: out signed(9 downto 0);
  signal F_rnd1_RE: out std_logic;
  signal F_rnd1_RD: in std_logic_vector(9 downto 0);
  signal F_rnd1_GD: in std_logic;
  signal RAM_b_DIN: out std_logic_vector(7 downto 0);
  signal RAM_b_WE: out std_logic;
  signal RAM_b_DOUT: in std_logic_vector(7 downto 0);
  signal RAM_b_RE: out std_logic;
  signal RAM_b_ADDR: out std_logic_vector(1 downto 0);
  signal RAM_b_GD: in std_logic;
  signal PRO_p1_ENABLE: in std_logic;
  signal PRO_p1_END: out std_logic;
  signal conpro_system_clk: in std_logic;
  signal conpro_system_reset: in std_logic
);
end r_p1;
architecture main of r_p1 is
  -- Local and temporary data objects
  signal TEMP_0: signed(7 downto 0);
  signal LOOP_i_0: signed(4 downto 0);
  -- Auxilliary ALU signals
  -- State Processing
  type pro_states is (
    S_p1_start, -- PROCESS0[:0]
    S_i1_fun, -- FUN16077[r.cp:28]
    S_i2_assign, -- ASSIGN87757[r.cp:29]
    S_i3_assign, -- ASSIGN59662[r.cp:30]
    S_i3_assign_1, -- ASSIGN59662[r.cp:30]
    S_i4_fun, -- FUN47348[r.cp:31]
    S_i5_assign, -- ASSIGN16603[r.cp:32]
    S_i6_fun, -- FUN63574[r.cp:33]
    S_i7_assign, -- ASSIGN65705[r.cp:34]
    S_i8_for_loop, -- COUNT_LOOP2877[r.cp:37]
    S_i8_for_loop_cond, -- COUNT_LOOP2877[r.cp:37]
    S_i9_fun, -- FUN5427[r.cp:39]
    S_i10_bind_to_11, -- ASSIGN7669[r.cp:42]
    S_i8_for_loop_incr, -- COUNT_LOOP2877[r.cp:37]
    S_p1_end -- PROCESS0[:0]
    );
  signal pro_state: pro_states := S_p1_start;
  signal pro_state_next: pro_states := S_p1_start;
  -- Auxilliary toplevel definitions
  constant CONST_I8_1: signed(7 downto 0) := "00000001";
  constant CONST_I4_1: signed(3 downto 0) := "0001";
  constant CONST_I5_1: signed(4 downto 0) := "00001";
  constant CONST_I5_10: signed(4 downto 0) := "01010";
  signal LOOP_i_0_CONV_I10: signed(9 downto 0);
begin
  state_transition: process(
          PRO_p1_ENABLE,
          pro_state_next,
          conpro_system_clk,
          conpro_system_reset
  )
  begin
    if conpro_system_clk'event and conpro_system_clk='1' then
      if conpro_system_reset='1' or PRO_p1_ENABLE='0' then
        pro_state <= S_p1_start;
      else
        pro_state <= pro_state_next;
      end if;
    end if;
  end process state_transition;
  -- Process implementation
  -- Instruction Controlpath Unit - The Leitwerk
  control_path: process(
          F_rnd1_GD,
          RAM_b_GD,
          LOOP_i_0,
          pro_state
          )
  begin
    PRO_p1_END <= '0';
    case pro_state is
      when S_p1_start => -- PROCESS0[:0]
        pro_state_next <= S_i1_fun;
      when S_i1_fun => -- FUN16077[r.cp:28]
        if not((F_rnd1_GD) = ('0')) then
          pro_state_next <= S_i1_fun;
        else
          pro_state_next <= S_i2_assign;
        end if;
      when S_i2_assign => -- ASSIGN87757[r.cp:29]
        pro_state_next <= S_i3_assign;
      when S_i3_assign => -- ASSIGN59662[r.cp:30]
        if RAM_b_GD = '1' then
          pro_state_next <= S_i3_assign;
        else
          pro_state_next <= S_i3_assign_1;
        end if;
      when S_i3_assign_1 => -- ASSIGN59662[r.cp:30]
        if RAM_b_GD = '1' then
          pro_state_next <= S_i3_assign_1;
        else
          pro_state_next <= S_i4_fun;
        end if;
      when S_i4_fun => -- FUN47348[r.cp:31]
        if not((F_rnd1_GD) = ('0')) then
          pro_state_next <= S_i4_fun;
        else
          pro_state_next <= S_i5_assign;
        end if;
      when S_i5_assign => -- ASSIGN16603[r.cp:32]
        pro_state_next <= S_i6_fun;
      when S_i6_fun => -- FUN63574[r.cp:33]
        if not((F_rnd1_GD) = ('0')) then
          pro_state_next <= S_i6_fun;
        else
          pro_state_next <= S_i7_assign;
        end if;
      when S_i7_assign => -- ASSIGN65705[r.cp:34]
        pro_state_next <= S_i8_for_loop;
      when S_i8_for_loop => -- COUNT_LOOP2877[r.cp:37]
        pro_state_next <= S_i8_for_loop_cond;
      when S_i8_for_loop_cond => -- COUNT_LOOP2877[r.cp:37]
        if CONST_I5_10 >= LOOP_i_0 then
          pro_state_next <= S_i9_fun;
        else
          pro_state_next <= S_p1_end;
        end if;
      when S_i9_fun => -- FUN5427[r.cp:39]
        if not((F_rnd1_GD) = ('0')) then
          pro_state_next <= S_i9_fun;
        else
          pro_state_next <= S_i10_bind_to_11;
        end if;
      when S_i10_bind_to_11 => -- ASSIGN7669[r.cp:42]
        pro_state_next <= S_i8_for_loop_incr;
      when S_i8_for_loop_incr => -- COUNT_LOOP2877[r.cp:37]
        pro_state_next <= S_i8_for_loop_cond;
      when S_p1_end => -- PROCESS0[:0]
        pro_state_next <= S_p1_end;
        PRO_p1_END <= '1';
    end case;
  end process control_path;
  
  -- Instruction Datapath Combinational Unit
  data_path: process(
          F_rnd1_RD,
          REG_e_RD,
          TEMP_0,
          REG_f_RD,
          REG_g_RD,
          REG_d_RD,
          LOOP_i_0_CONV_I10,
          LOOP_i_0,
          pro_state
          )
  begin
    -- Default values
    F_rnd1_RE <= '0';
    REG_e_WR <= "000000000000";
    REG_e_WE <= '0';
    RAM_b_RE <= '0';
    RAM_b_ADDR <= "00";
    RAM_b_WE <= '0';
    RAM_b_DIN <= "00000000";
    REG_f_WR <= to_signed(0,4);
    REG_f_WE <= '0';
    REG_g_WR <= "0000";
    REG_g_WE <= '0';
    REG_d_WR <= to_signed(0,10);
    REG_d_WE <= '0';
    y_WR <= to_signed(0,10);
    x_WR <= to_signed(0,10);
    case pro_state is
      when S_p1_start => -- PROCESS0[:0]
        null;
      when S_i1_fun => -- FUN16077[r.cp:28]
        F_rnd1_RE <= '1';
        REG_e_WR <= ("00" & F_rnd1_RD);
        REG_e_WE <= not F_rnd1_GD;
      when S_i2_assign => -- ASSIGN87757[r.cp:29]
        REG_e_WR <= REG_e_RD + "000000000001";
        REG_e_WE <= '1';
      when S_i3_assign => -- ASSIGN59662[r.cp:30]
        RAM_b_RE <= '1';
        RAM_b_ADDR <= "00"; -- v
      when S_i3_assign_1 => -- ASSIGN59662[r.cp:30]
        RAM_b_DIN <= std_logic_vector(TEMP_0 + CONST_I8_1);
        RAM_b_WE <= '1';
        RAM_b_ADDR <= "00"; -- v
      when S_i4_fun => -- FUN47348[r.cp:31]
        F_rnd1_RE <= '1';
        REG_f_WR <= resize(signed(F_rnd1_RD),4);
        REG_f_WE <= not F_rnd1_GD;
      when S_i5_assign => -- ASSIGN16603[r.cp:32]
        REG_f_WR <= REG_f_RD + CONST_I4_1;
        REG_f_WE <= '1';
      when S_i6_fun => -- FUN63574[r.cp:33]
        F_rnd1_RE <= '1';
        REG_g_WR <= F_rnd1_RD(3 downto 0);
        REG_g_WE <= not F_rnd1_GD;
      when S_i7_assign => -- ASSIGN65705[r.cp:34]
        REG_g_WR <= REG_g_RD + "0001";
        REG_g_WE <= '1';
      when S_i8_for_loop => -- COUNT_LOOP2877[r.cp:37]
        null;
      when S_i8_for_loop_cond => -- COUNT_LOOP2877[r.cp:37]
        null;
      when S_i9_fun => -- FUN5427[r.cp:39]
        F_rnd1_RE <= '1';
        REG_d_WR <= signed(F_rnd1_RD);
        REG_d_WE <= not F_rnd1_GD;
      when S_i10_bind_to_11 => -- ASSIGN7669[r.cp:42]
        y_WR <= REG_d_RD;
        x_WR <= LOOP_i_0_CONV_I10;
      when S_i8_for_loop_incr => -- COUNT_LOOP2877[r.cp:37]
        null;
      when S_p1_end => -- PROCESS0[:0]
        null;
    end case;
  end process data_path;
  
  -- Instruction Datapath Transitional Unit
  data_trans: process(
          RAM_b_DOUT,
          conpro_system_clk,
          conpro_system_reset,
          pro_state
          )
  begin
    if conpro_system_clk'event and conpro_system_clk='1' then
      if conpro_system_reset = '1' then
        TEMP_0 <= to_signed(0,8);
        LOOP_i_0 <= to_signed(0,5);
      else
        case pro_state is
          when S_p1_start => -- PROCESS0[:0]
            null;
          when S_i1_fun => -- FUN16077[r.cp:28]
            null;
          when S_i2_assign => -- ASSIGN87757[r.cp:29]
            null;
          when S_i3_assign => -- ASSIGN59662[r.cp:30]
            TEMP_0 <= signed(RAM_b_DOUT);
          when S_i3_assign_1 => -- ASSIGN59662[r.cp:30]
            null;
          when S_i4_fun => -- FUN47348[r.cp:31]
            null;
          when S_i5_assign => -- ASSIGN16603[r.cp:32]
            null;
          when S_i6_fun => -- FUN63574[r.cp:33]
            null;
          when S_i7_assign => -- ASSIGN65705[r.cp:34]
            null;
          when S_i8_for_loop => -- COUNT_LOOP2877[r.cp:37]
            LOOP_i_0 <= CONST_I5_1;
          when S_i8_for_loop_cond => -- COUNT_LOOP2877[r.cp:37]
            null;
          when S_i9_fun => -- FUN5427[r.cp:39]
            null;
          when S_i10_bind_to_11 => -- ASSIGN7669[r.cp:42]
            null;
          when S_i8_for_loop_incr => -- COUNT_LOOP2877[r.cp:37]
            LOOP_i_0 <= LOOP_i_0 + CONST_I5_1;
          when S_p1_end => -- PROCESS0[:0]
            null;
        end case;
      end if;
    end if;
  end process data_trans;
  
  -- Object implementation
  
  -- Toplevel assignments
  -- Monitors
  LOOP_i_0_CONV_I10 <= resize(LOOP_i_0,10);
end main;
